// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Block_ap_fixed_base_s_HH_
#define _Block_ap_fixed_base_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Block_ap_fixed_base_s : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > Stage0_COS_V_V_din;
    sc_in< sc_logic > Stage0_COS_V_V_full_n;
    sc_out< sc_logic > Stage0_COS_V_V_write;
    sc_out< sc_lv<10> > Stage0_Sin_V_V_din;
    sc_in< sc_logic > Stage0_Sin_V_V_full_n;
    sc_out< sc_logic > Stage0_Sin_V_V_write;


    // Module declarations
    Block_ap_fixed_base_s(sc_module_name name);
    SC_HAS_PROCESS(Block_ap_fixed_base_s);

    ~Block_ap_fixed_base_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > Stage0_COS_V_V_blk_n;
    sc_signal< sc_logic > Stage0_Sin_V_V_blk_n;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<10> ap_const_lv10_136;
    static const sc_lv<10> ap_const_lv10_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_Stage0_COS_V_V_blk_n();
    void thread_Stage0_COS_V_V_din();
    void thread_Stage0_COS_V_V_write();
    void thread_Stage0_Sin_V_V_blk_n();
    void thread_Stage0_Sin_V_V_din();
    void thread_Stage0_Sin_V_V_write();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
