// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cordic,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.365000,HLS_SYN_LAT=31,HLS_SYN_TPT=2,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1040,HLS_SYN_LUT=4191,HLS_VERSION=2020_1}" *)

module cordic (
        in_theta_V_V_dout,
        in_theta_V_V_empty_n,
        in_theta_V_V_read,
        out_s_V_V_din,
        out_s_V_V_full_n,
        out_s_V_V_write,
        out_c_V_V_din,
        out_c_V_V_full_n,
        out_c_V_V_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [9:0] in_theta_V_V_dout;
input   in_theta_V_V_empty_n;
output   in_theta_V_V_read;
output  [9:0] out_s_V_V_din;
input   out_s_V_V_full_n;
output   out_s_V_V_write;
output  [9:0] out_c_V_V_din;
input   out_c_V_V_full_n;
output   out_c_V_V_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Block_ap_fixed_base_U0_ap_start;
wire    Block_ap_fixed_base_U0_ap_done;
wire    Block_ap_fixed_base_U0_ap_continue;
wire    Block_ap_fixed_base_U0_ap_idle;
wire    Block_ap_fixed_base_U0_ap_ready;
wire   [9:0] Block_ap_fixed_base_U0_Stage0_COS_V_V_din;
wire    Block_ap_fixed_base_U0_Stage0_COS_V_V_write;
wire   [9:0] Block_ap_fixed_base_U0_Stage0_Sin_V_V_din;
wire    Block_ap_fixed_base_U0_Stage0_Sin_V_V_write;
wire    one_stage20_U0_ap_start;
wire    one_stage20_U0_ap_done;
wire    one_stage20_U0_ap_continue;
wire    one_stage20_U0_ap_idle;
wire    one_stage20_U0_ap_ready;
wire    one_stage20_U0_start_out;
wire    one_stage20_U0_start_write;
wire    one_stage20_U0_s_current_cos_V_V_read;
wire    one_stage20_U0_s_current_sin_V_V_read;
wire    one_stage20_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage20_U0_s_output_cos_V_V_din;
wire    one_stage20_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage20_U0_s_output_sin_V_V_din;
wire    one_stage20_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage20_U0_s_output_theta_V_V_din;
wire    one_stage20_U0_s_output_theta_V_V_write;
wire    one_stage21_U0_ap_start;
wire    one_stage21_U0_ap_done;
wire    one_stage21_U0_ap_continue;
wire    one_stage21_U0_ap_idle;
wire    one_stage21_U0_ap_ready;
wire    one_stage21_U0_start_out;
wire    one_stage21_U0_start_write;
wire    one_stage21_U0_s_current_cos_V_V_read;
wire    one_stage21_U0_s_current_sin_V_V_read;
wire    one_stage21_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage21_U0_s_output_cos_V_V_din;
wire    one_stage21_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage21_U0_s_output_sin_V_V_din;
wire    one_stage21_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage21_U0_s_output_theta_V_V_din;
wire    one_stage21_U0_s_output_theta_V_V_write;
wire    one_stage22_U0_ap_start;
wire    one_stage22_U0_ap_done;
wire    one_stage22_U0_ap_continue;
wire    one_stage22_U0_ap_idle;
wire    one_stage22_U0_ap_ready;
wire    one_stage22_U0_start_out;
wire    one_stage22_U0_start_write;
wire    one_stage22_U0_s_current_cos_V_V_read;
wire    one_stage22_U0_s_current_sin_V_V_read;
wire    one_stage22_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage22_U0_s_output_cos_V_V_din;
wire    one_stage22_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage22_U0_s_output_sin_V_V_din;
wire    one_stage22_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage22_U0_s_output_theta_V_V_din;
wire    one_stage22_U0_s_output_theta_V_V_write;
wire    one_stage23_U0_ap_start;
wire    one_stage23_U0_ap_done;
wire    one_stage23_U0_ap_continue;
wire    one_stage23_U0_ap_idle;
wire    one_stage23_U0_ap_ready;
wire    one_stage23_U0_start_out;
wire    one_stage23_U0_start_write;
wire    one_stage23_U0_s_current_cos_V_V_read;
wire    one_stage23_U0_s_current_sin_V_V_read;
wire    one_stage23_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage23_U0_s_output_cos_V_V_din;
wire    one_stage23_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage23_U0_s_output_sin_V_V_din;
wire    one_stage23_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage23_U0_s_output_theta_V_V_din;
wire    one_stage23_U0_s_output_theta_V_V_write;
wire    one_stage24_U0_ap_start;
wire    one_stage24_U0_ap_done;
wire    one_stage24_U0_ap_continue;
wire    one_stage24_U0_ap_idle;
wire    one_stage24_U0_ap_ready;
wire    one_stage24_U0_start_out;
wire    one_stage24_U0_start_write;
wire    one_stage24_U0_s_current_cos_V_V_read;
wire    one_stage24_U0_s_current_sin_V_V_read;
wire    one_stage24_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage24_U0_s_output_cos_V_V_din;
wire    one_stage24_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage24_U0_s_output_sin_V_V_din;
wire    one_stage24_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage24_U0_s_output_theta_V_V_din;
wire    one_stage24_U0_s_output_theta_V_V_write;
wire    one_stage25_U0_ap_start;
wire    one_stage25_U0_ap_done;
wire    one_stage25_U0_ap_continue;
wire    one_stage25_U0_ap_idle;
wire    one_stage25_U0_ap_ready;
wire    one_stage25_U0_start_out;
wire    one_stage25_U0_start_write;
wire    one_stage25_U0_s_current_cos_V_V_read;
wire    one_stage25_U0_s_current_sin_V_V_read;
wire    one_stage25_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage25_U0_s_output_cos_V_V_din;
wire    one_stage25_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage25_U0_s_output_sin_V_V_din;
wire    one_stage25_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage25_U0_s_output_theta_V_V_din;
wire    one_stage25_U0_s_output_theta_V_V_write;
wire    one_stage26_U0_ap_start;
wire    one_stage26_U0_ap_done;
wire    one_stage26_U0_ap_continue;
wire    one_stage26_U0_ap_idle;
wire    one_stage26_U0_ap_ready;
wire    one_stage26_U0_start_out;
wire    one_stage26_U0_start_write;
wire    one_stage26_U0_s_current_cos_V_V_read;
wire    one_stage26_U0_s_current_sin_V_V_read;
wire    one_stage26_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage26_U0_s_output_cos_V_V_din;
wire    one_stage26_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage26_U0_s_output_sin_V_V_din;
wire    one_stage26_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage26_U0_s_output_theta_V_V_din;
wire    one_stage26_U0_s_output_theta_V_V_write;
wire    one_stage27_U0_ap_start;
wire    one_stage27_U0_ap_done;
wire    one_stage27_U0_ap_continue;
wire    one_stage27_U0_ap_idle;
wire    one_stage27_U0_ap_ready;
wire    one_stage27_U0_start_out;
wire    one_stage27_U0_start_write;
wire    one_stage27_U0_s_current_cos_V_V_read;
wire    one_stage27_U0_s_current_sin_V_V_read;
wire    one_stage27_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage27_U0_s_output_cos_V_V_din;
wire    one_stage27_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage27_U0_s_output_sin_V_V_din;
wire    one_stage27_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage27_U0_s_output_theta_V_V_din;
wire    one_stage27_U0_s_output_theta_V_V_write;
wire    one_stage28_U0_ap_start;
wire    one_stage28_U0_ap_done;
wire    one_stage28_U0_ap_continue;
wire    one_stage28_U0_ap_idle;
wire    one_stage28_U0_ap_ready;
wire    one_stage28_U0_start_out;
wire    one_stage28_U0_start_write;
wire    one_stage28_U0_s_current_cos_V_V_read;
wire    one_stage28_U0_s_current_sin_V_V_read;
wire    one_stage28_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage28_U0_s_output_cos_V_V_din;
wire    one_stage28_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage28_U0_s_output_sin_V_V_din;
wire    one_stage28_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage28_U0_s_output_theta_V_V_din;
wire    one_stage28_U0_s_output_theta_V_V_write;
wire    one_stage29_U0_ap_start;
wire    one_stage29_U0_ap_done;
wire    one_stage29_U0_ap_continue;
wire    one_stage29_U0_ap_idle;
wire    one_stage29_U0_ap_ready;
wire    one_stage29_U0_start_out;
wire    one_stage29_U0_start_write;
wire    one_stage29_U0_s_current_cos_V_V_read;
wire    one_stage29_U0_s_current_sin_V_V_read;
wire    one_stage29_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage29_U0_s_output_cos_V_V_din;
wire    one_stage29_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage29_U0_s_output_sin_V_V_din;
wire    one_stage29_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage29_U0_s_output_theta_V_V_din;
wire    one_stage29_U0_s_output_theta_V_V_write;
wire    one_stage30_U0_ap_start;
wire    one_stage30_U0_ap_done;
wire    one_stage30_U0_ap_continue;
wire    one_stage30_U0_ap_idle;
wire    one_stage30_U0_ap_ready;
wire    one_stage30_U0_start_out;
wire    one_stage30_U0_start_write;
wire    one_stage30_U0_s_current_cos_V_V_read;
wire    one_stage30_U0_s_current_sin_V_V_read;
wire    one_stage30_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage30_U0_s_output_cos_V_V_din;
wire    one_stage30_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage30_U0_s_output_sin_V_V_din;
wire    one_stage30_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage30_U0_s_output_theta_V_V_din;
wire    one_stage30_U0_s_output_theta_V_V_write;
wire    one_stage31_U0_ap_start;
wire    one_stage31_U0_ap_done;
wire    one_stage31_U0_ap_continue;
wire    one_stage31_U0_ap_idle;
wire    one_stage31_U0_ap_ready;
wire    one_stage31_U0_start_out;
wire    one_stage31_U0_start_write;
wire    one_stage31_U0_s_current_cos_V_V_read;
wire    one_stage31_U0_s_current_sin_V_V_read;
wire    one_stage31_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage31_U0_s_output_cos_V_V_din;
wire    one_stage31_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage31_U0_s_output_sin_V_V_din;
wire    one_stage31_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage31_U0_s_output_theta_V_V_din;
wire    one_stage31_U0_s_output_theta_V_V_write;
wire    one_stage32_U0_ap_start;
wire    one_stage32_U0_ap_done;
wire    one_stage32_U0_ap_continue;
wire    one_stage32_U0_ap_idle;
wire    one_stage32_U0_ap_ready;
wire    one_stage32_U0_start_out;
wire    one_stage32_U0_start_write;
wire    one_stage32_U0_s_current_cos_V_V_read;
wire    one_stage32_U0_s_current_sin_V_V_read;
wire    one_stage32_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage32_U0_s_output_cos_V_V_din;
wire    one_stage32_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage32_U0_s_output_sin_V_V_din;
wire    one_stage32_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage32_U0_s_output_theta_V_V_din;
wire    one_stage32_U0_s_output_theta_V_V_write;
wire    one_stage33_U0_ap_start;
wire    one_stage33_U0_ap_done;
wire    one_stage33_U0_ap_continue;
wire    one_stage33_U0_ap_idle;
wire    one_stage33_U0_ap_ready;
wire    one_stage33_U0_start_out;
wire    one_stage33_U0_start_write;
wire    one_stage33_U0_s_current_cos_V_V_read;
wire    one_stage33_U0_s_current_sin_V_V_read;
wire    one_stage33_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage33_U0_s_output_cos_V_V_din;
wire    one_stage33_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage33_U0_s_output_sin_V_V_din;
wire    one_stage33_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage33_U0_s_output_theta_V_V_din;
wire    one_stage33_U0_s_output_theta_V_V_write;
wire    one_stage34_U0_ap_start;
wire    one_stage34_U0_ap_done;
wire    one_stage34_U0_ap_continue;
wire    one_stage34_U0_ap_idle;
wire    one_stage34_U0_ap_ready;
wire    one_stage34_U0_start_out;
wire    one_stage34_U0_start_write;
wire    one_stage34_U0_s_current_cos_V_V_read;
wire    one_stage34_U0_s_current_sin_V_V_read;
wire    one_stage34_U0_s_current_theta_V_V_read;
wire   [9:0] one_stage34_U0_s_output_cos_V_V_din;
wire    one_stage34_U0_s_output_cos_V_V_write;
wire   [9:0] one_stage34_U0_s_output_sin_V_V_din;
wire    one_stage34_U0_s_output_sin_V_V_write;
wire   [9:0] one_stage34_U0_s_output_theta_V_V_din;
wire    one_stage34_U0_s_output_theta_V_V_write;
wire    ap_sync_continue;
wire    Block_ap_fixed_base_1_U0_ap_start;
wire    Block_ap_fixed_base_1_U0_ap_done;
wire    Block_ap_fixed_base_1_U0_ap_continue;
wire    Block_ap_fixed_base_1_U0_ap_idle;
wire    Block_ap_fixed_base_1_U0_ap_ready;
wire    Block_ap_fixed_base_1_U0_Theta16_V_V_read;
wire    Stage0_COS_V_V_full_n;
wire   [9:0] Stage0_COS_V_V_dout;
wire    Stage0_COS_V_V_empty_n;
wire    Stage0_Sin_V_V_full_n;
wire   [9:0] Stage0_Sin_V_V_dout;
wire    Stage0_Sin_V_V_empty_n;
wire    Stage1_COS_V_V_full_n;
wire   [9:0] Stage1_COS_V_V_dout;
wire    Stage1_COS_V_V_empty_n;
wire    Stage1_Sin_V_V_full_n;
wire   [9:0] Stage1_Sin_V_V_dout;
wire    Stage1_Sin_V_V_empty_n;
wire    Theta2_V_V_full_n;
wire   [9:0] Theta2_V_V_dout;
wire    Theta2_V_V_empty_n;
wire    Stage2_COS_V_V_full_n;
wire   [9:0] Stage2_COS_V_V_dout;
wire    Stage2_COS_V_V_empty_n;
wire    Stage2_Sin_V_V_full_n;
wire   [9:0] Stage2_Sin_V_V_dout;
wire    Stage2_Sin_V_V_empty_n;
wire    Theta3_V_V_full_n;
wire   [9:0] Theta3_V_V_dout;
wire    Theta3_V_V_empty_n;
wire    Stage3_COS_V_V_full_n;
wire   [9:0] Stage3_COS_V_V_dout;
wire    Stage3_COS_V_V_empty_n;
wire    Stage3_Sin_V_V_full_n;
wire   [9:0] Stage3_Sin_V_V_dout;
wire    Stage3_Sin_V_V_empty_n;
wire    Theta4_V_V_full_n;
wire   [9:0] Theta4_V_V_dout;
wire    Theta4_V_V_empty_n;
wire    Stage4_COS_V_V_full_n;
wire   [9:0] Stage4_COS_V_V_dout;
wire    Stage4_COS_V_V_empty_n;
wire    Stage4_Sin_V_V_full_n;
wire   [9:0] Stage4_Sin_V_V_dout;
wire    Stage4_Sin_V_V_empty_n;
wire    Theta5_V_V_full_n;
wire   [9:0] Theta5_V_V_dout;
wire    Theta5_V_V_empty_n;
wire    Stage5_COS_V_V_full_n;
wire   [9:0] Stage5_COS_V_V_dout;
wire    Stage5_COS_V_V_empty_n;
wire    Stage5_Sin_V_V_full_n;
wire   [9:0] Stage5_Sin_V_V_dout;
wire    Stage5_Sin_V_V_empty_n;
wire    Theta6_V_V_full_n;
wire   [9:0] Theta6_V_V_dout;
wire    Theta6_V_V_empty_n;
wire    Stage6_COS_V_V_full_n;
wire   [9:0] Stage6_COS_V_V_dout;
wire    Stage6_COS_V_V_empty_n;
wire    Stage6_Sin_V_V_full_n;
wire   [9:0] Stage6_Sin_V_V_dout;
wire    Stage6_Sin_V_V_empty_n;
wire    Theta7_V_V_full_n;
wire   [9:0] Theta7_V_V_dout;
wire    Theta7_V_V_empty_n;
wire    Stage7_COS_V_V_full_n;
wire   [9:0] Stage7_COS_V_V_dout;
wire    Stage7_COS_V_V_empty_n;
wire    Stage7_Sin_V_V_full_n;
wire   [9:0] Stage7_Sin_V_V_dout;
wire    Stage7_Sin_V_V_empty_n;
wire    Theta8_V_V_full_n;
wire   [9:0] Theta8_V_V_dout;
wire    Theta8_V_V_empty_n;
wire    Stage8_COS_V_V_full_n;
wire   [9:0] Stage8_COS_V_V_dout;
wire    Stage8_COS_V_V_empty_n;
wire    Stage8_Sin_V_V_full_n;
wire   [9:0] Stage8_Sin_V_V_dout;
wire    Stage8_Sin_V_V_empty_n;
wire    Theta9_V_V_full_n;
wire   [9:0] Theta9_V_V_dout;
wire    Theta9_V_V_empty_n;
wire    Stage9_COS_V_V_full_n;
wire   [9:0] Stage9_COS_V_V_dout;
wire    Stage9_COS_V_V_empty_n;
wire    Stage9_Sin_V_V_full_n;
wire   [9:0] Stage9_Sin_V_V_dout;
wire    Stage9_Sin_V_V_empty_n;
wire    Theta10_V_V_full_n;
wire   [9:0] Theta10_V_V_dout;
wire    Theta10_V_V_empty_n;
wire    Stage10_COS_V_V_full_n;
wire   [9:0] Stage10_COS_V_V_dout;
wire    Stage10_COS_V_V_empty_n;
wire    Stage10_Sin_V_V_full_n;
wire   [9:0] Stage10_Sin_V_V_dout;
wire    Stage10_Sin_V_V_empty_n;
wire    Theta11_V_V_full_n;
wire   [9:0] Theta11_V_V_dout;
wire    Theta11_V_V_empty_n;
wire    Stage11_COS_V_V_full_n;
wire   [9:0] Stage11_COS_V_V_dout;
wire    Stage11_COS_V_V_empty_n;
wire    Stage11_Sin_V_V_full_n;
wire   [9:0] Stage11_Sin_V_V_dout;
wire    Stage11_Sin_V_V_empty_n;
wire    Theta12_V_V_full_n;
wire   [9:0] Theta12_V_V_dout;
wire    Theta12_V_V_empty_n;
wire    Stage12_COS_V_V_full_n;
wire   [9:0] Stage12_COS_V_V_dout;
wire    Stage12_COS_V_V_empty_n;
wire    Stage12_Sin_V_V_full_n;
wire   [9:0] Stage12_Sin_V_V_dout;
wire    Stage12_Sin_V_V_empty_n;
wire    Theta13_V_V_full_n;
wire   [9:0] Theta13_V_V_dout;
wire    Theta13_V_V_empty_n;
wire    Stage13_COS_V_V_full_n;
wire   [9:0] Stage13_COS_V_V_dout;
wire    Stage13_COS_V_V_empty_n;
wire    Stage13_Sin_V_V_full_n;
wire   [9:0] Stage13_Sin_V_V_dout;
wire    Stage13_Sin_V_V_empty_n;
wire    Theta14_V_V_full_n;
wire   [9:0] Theta14_V_V_dout;
wire    Theta14_V_V_empty_n;
wire    Stage14_COS_V_V_full_n;
wire   [9:0] Stage14_COS_V_V_dout;
wire    Stage14_COS_V_V_empty_n;
wire    Stage14_Sin_V_V_full_n;
wire   [9:0] Stage14_Sin_V_V_dout;
wire    Stage14_Sin_V_V_empty_n;
wire    Theta15_V_V_full_n;
wire   [9:0] Theta15_V_V_dout;
wire    Theta15_V_V_empty_n;
wire    Theta16_V_V_full_n;
wire   [9:0] Theta16_V_V_dout;
wire    Theta16_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_ap_fixed_base_U0_ap_ready;
wire    ap_sync_Block_ap_fixed_base_U0_ap_ready;
reg   [1:0] Block_ap_fixed_base_U0_ap_ready_count;
reg    ap_sync_reg_one_stage20_U0_ap_ready;
wire    ap_sync_one_stage20_U0_ap_ready;
reg   [1:0] one_stage20_U0_ap_ready_count;
wire    Block_ap_fixed_base_U0_start_full_n;
wire    Block_ap_fixed_base_U0_start_write;
wire   [0:0] start_for_one_stage21_U0_din;
wire    start_for_one_stage21_U0_full_n;
wire   [0:0] start_for_one_stage21_U0_dout;
wire    start_for_one_stage21_U0_empty_n;
wire   [0:0] start_for_one_stage22_U0_din;
wire    start_for_one_stage22_U0_full_n;
wire   [0:0] start_for_one_stage22_U0_dout;
wire    start_for_one_stage22_U0_empty_n;
wire   [0:0] start_for_one_stage23_U0_din;
wire    start_for_one_stage23_U0_full_n;
wire   [0:0] start_for_one_stage23_U0_dout;
wire    start_for_one_stage23_U0_empty_n;
wire   [0:0] start_for_one_stage24_U0_din;
wire    start_for_one_stage24_U0_full_n;
wire   [0:0] start_for_one_stage24_U0_dout;
wire    start_for_one_stage24_U0_empty_n;
wire   [0:0] start_for_one_stage25_U0_din;
wire    start_for_one_stage25_U0_full_n;
wire   [0:0] start_for_one_stage25_U0_dout;
wire    start_for_one_stage25_U0_empty_n;
wire   [0:0] start_for_one_stage26_U0_din;
wire    start_for_one_stage26_U0_full_n;
wire   [0:0] start_for_one_stage26_U0_dout;
wire    start_for_one_stage26_U0_empty_n;
wire   [0:0] start_for_one_stage27_U0_din;
wire    start_for_one_stage27_U0_full_n;
wire   [0:0] start_for_one_stage27_U0_dout;
wire    start_for_one_stage27_U0_empty_n;
wire   [0:0] start_for_one_stage28_U0_din;
wire    start_for_one_stage28_U0_full_n;
wire   [0:0] start_for_one_stage28_U0_dout;
wire    start_for_one_stage28_U0_empty_n;
wire   [0:0] start_for_one_stage29_U0_din;
wire    start_for_one_stage29_U0_full_n;
wire   [0:0] start_for_one_stage29_U0_dout;
wire    start_for_one_stage29_U0_empty_n;
wire   [0:0] start_for_one_stage30_U0_din;
wire    start_for_one_stage30_U0_full_n;
wire   [0:0] start_for_one_stage30_U0_dout;
wire    start_for_one_stage30_U0_empty_n;
wire   [0:0] start_for_one_stage31_U0_din;
wire    start_for_one_stage31_U0_full_n;
wire   [0:0] start_for_one_stage31_U0_dout;
wire    start_for_one_stage31_U0_empty_n;
wire   [0:0] start_for_one_stage32_U0_din;
wire    start_for_one_stage32_U0_full_n;
wire   [0:0] start_for_one_stage32_U0_dout;
wire    start_for_one_stage32_U0_empty_n;
wire   [0:0] start_for_one_stage33_U0_din;
wire    start_for_one_stage33_U0_full_n;
wire   [0:0] start_for_one_stage33_U0_dout;
wire    start_for_one_stage33_U0_empty_n;
wire   [0:0] start_for_one_stage34_U0_din;
wire    start_for_one_stage34_U0_full_n;
wire   [0:0] start_for_one_stage34_U0_dout;
wire    start_for_one_stage34_U0_empty_n;
wire   [0:0] start_for_Block_ap_fixed_base_1_U0_din;
wire    start_for_Block_ap_fixed_base_1_U0_full_n;
wire   [0:0] start_for_Block_ap_fixed_base_1_U0_dout;
wire    start_for_Block_ap_fixed_base_1_U0_empty_n;
wire    Block_ap_fixed_base_1_U0_start_full_n;
wire    Block_ap_fixed_base_1_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_ap_fixed_base_U0_ap_ready = 1'b0;
#0 Block_ap_fixed_base_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_one_stage20_U0_ap_ready = 1'b0;
#0 one_stage20_U0_ap_ready_count = 2'd0;
end

Block_ap_fixed_base_s Block_ap_fixed_base_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_ap_fixed_base_U0_ap_start),
    .ap_done(Block_ap_fixed_base_U0_ap_done),
    .ap_continue(Block_ap_fixed_base_U0_ap_continue),
    .ap_idle(Block_ap_fixed_base_U0_ap_idle),
    .ap_ready(Block_ap_fixed_base_U0_ap_ready),
    .Stage0_COS_V_V_din(Block_ap_fixed_base_U0_Stage0_COS_V_V_din),
    .Stage0_COS_V_V_full_n(Stage0_COS_V_V_full_n),
    .Stage0_COS_V_V_write(Block_ap_fixed_base_U0_Stage0_COS_V_V_write),
    .Stage0_Sin_V_V_din(Block_ap_fixed_base_U0_Stage0_Sin_V_V_din),
    .Stage0_Sin_V_V_full_n(Stage0_Sin_V_V_full_n),
    .Stage0_Sin_V_V_write(Block_ap_fixed_base_U0_Stage0_Sin_V_V_write)
);

one_stage20 one_stage20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage20_U0_ap_start),
    .start_full_n(start_for_one_stage21_U0_full_n),
    .ap_done(one_stage20_U0_ap_done),
    .ap_continue(one_stage20_U0_ap_continue),
    .ap_idle(one_stage20_U0_ap_idle),
    .ap_ready(one_stage20_U0_ap_ready),
    .start_out(one_stage20_U0_start_out),
    .start_write(one_stage20_U0_start_write),
    .s_current_cos_V_V_dout(Stage0_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage0_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage20_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage0_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage0_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage20_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(in_theta_V_V_dout),
    .s_current_theta_V_V_empty_n(in_theta_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage20_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage20_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage1_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage20_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage20_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage1_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage20_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage20_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta2_V_V_full_n),
    .s_output_theta_V_V_write(one_stage20_U0_s_output_theta_V_V_write)
);

one_stage21 one_stage21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage21_U0_ap_start),
    .start_full_n(start_for_one_stage22_U0_full_n),
    .ap_done(one_stage21_U0_ap_done),
    .ap_continue(one_stage21_U0_ap_continue),
    .ap_idle(one_stage21_U0_ap_idle),
    .ap_ready(one_stage21_U0_ap_ready),
    .start_out(one_stage21_U0_start_out),
    .start_write(one_stage21_U0_start_write),
    .s_current_cos_V_V_dout(Stage1_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage1_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage21_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage1_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage1_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage21_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta2_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta2_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage21_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage21_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage2_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage21_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage21_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage2_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage21_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage21_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta3_V_V_full_n),
    .s_output_theta_V_V_write(one_stage21_U0_s_output_theta_V_V_write)
);

one_stage22 one_stage22_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage22_U0_ap_start),
    .start_full_n(start_for_one_stage23_U0_full_n),
    .ap_done(one_stage22_U0_ap_done),
    .ap_continue(one_stage22_U0_ap_continue),
    .ap_idle(one_stage22_U0_ap_idle),
    .ap_ready(one_stage22_U0_ap_ready),
    .start_out(one_stage22_U0_start_out),
    .start_write(one_stage22_U0_start_write),
    .s_current_cos_V_V_dout(Stage2_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage2_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage22_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage2_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage2_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage22_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta3_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta3_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage22_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage22_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage3_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage22_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage22_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage3_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage22_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage22_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta4_V_V_full_n),
    .s_output_theta_V_V_write(one_stage22_U0_s_output_theta_V_V_write)
);

one_stage23 one_stage23_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage23_U0_ap_start),
    .start_full_n(start_for_one_stage24_U0_full_n),
    .ap_done(one_stage23_U0_ap_done),
    .ap_continue(one_stage23_U0_ap_continue),
    .ap_idle(one_stage23_U0_ap_idle),
    .ap_ready(one_stage23_U0_ap_ready),
    .start_out(one_stage23_U0_start_out),
    .start_write(one_stage23_U0_start_write),
    .s_current_cos_V_V_dout(Stage3_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage3_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage23_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage3_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage3_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage23_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta4_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta4_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage23_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage23_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage4_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage23_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage23_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage4_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage23_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage23_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta5_V_V_full_n),
    .s_output_theta_V_V_write(one_stage23_U0_s_output_theta_V_V_write)
);

one_stage24 one_stage24_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage24_U0_ap_start),
    .start_full_n(start_for_one_stage25_U0_full_n),
    .ap_done(one_stage24_U0_ap_done),
    .ap_continue(one_stage24_U0_ap_continue),
    .ap_idle(one_stage24_U0_ap_idle),
    .ap_ready(one_stage24_U0_ap_ready),
    .start_out(one_stage24_U0_start_out),
    .start_write(one_stage24_U0_start_write),
    .s_current_cos_V_V_dout(Stage4_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage4_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage24_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage4_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage4_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage24_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta5_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta5_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage24_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage24_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage5_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage24_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage24_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage5_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage24_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage24_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta6_V_V_full_n),
    .s_output_theta_V_V_write(one_stage24_U0_s_output_theta_V_V_write)
);

one_stage25 one_stage25_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage25_U0_ap_start),
    .start_full_n(start_for_one_stage26_U0_full_n),
    .ap_done(one_stage25_U0_ap_done),
    .ap_continue(one_stage25_U0_ap_continue),
    .ap_idle(one_stage25_U0_ap_idle),
    .ap_ready(one_stage25_U0_ap_ready),
    .start_out(one_stage25_U0_start_out),
    .start_write(one_stage25_U0_start_write),
    .s_current_cos_V_V_dout(Stage5_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage5_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage25_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage5_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage5_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage25_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta6_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta6_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage25_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage25_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage6_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage25_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage25_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage6_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage25_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage25_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta7_V_V_full_n),
    .s_output_theta_V_V_write(one_stage25_U0_s_output_theta_V_V_write)
);

one_stage26 one_stage26_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage26_U0_ap_start),
    .start_full_n(start_for_one_stage27_U0_full_n),
    .ap_done(one_stage26_U0_ap_done),
    .ap_continue(one_stage26_U0_ap_continue),
    .ap_idle(one_stage26_U0_ap_idle),
    .ap_ready(one_stage26_U0_ap_ready),
    .start_out(one_stage26_U0_start_out),
    .start_write(one_stage26_U0_start_write),
    .s_current_cos_V_V_dout(Stage6_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage6_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage26_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage6_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage6_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage26_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta7_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta7_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage26_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage26_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage7_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage26_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage26_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage7_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage26_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage26_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta8_V_V_full_n),
    .s_output_theta_V_V_write(one_stage26_U0_s_output_theta_V_V_write)
);

one_stage27 one_stage27_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage27_U0_ap_start),
    .start_full_n(start_for_one_stage28_U0_full_n),
    .ap_done(one_stage27_U0_ap_done),
    .ap_continue(one_stage27_U0_ap_continue),
    .ap_idle(one_stage27_U0_ap_idle),
    .ap_ready(one_stage27_U0_ap_ready),
    .start_out(one_stage27_U0_start_out),
    .start_write(one_stage27_U0_start_write),
    .s_current_cos_V_V_dout(Stage7_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage7_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage27_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage7_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage7_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage27_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta8_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta8_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage27_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage27_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage8_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage27_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage27_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage8_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage27_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage27_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta9_V_V_full_n),
    .s_output_theta_V_V_write(one_stage27_U0_s_output_theta_V_V_write)
);

one_stage28 one_stage28_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage28_U0_ap_start),
    .start_full_n(start_for_one_stage29_U0_full_n),
    .ap_done(one_stage28_U0_ap_done),
    .ap_continue(one_stage28_U0_ap_continue),
    .ap_idle(one_stage28_U0_ap_idle),
    .ap_ready(one_stage28_U0_ap_ready),
    .start_out(one_stage28_U0_start_out),
    .start_write(one_stage28_U0_start_write),
    .s_current_cos_V_V_dout(Stage8_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage8_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage28_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage8_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage8_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage28_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta9_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta9_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage28_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage28_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage9_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage28_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage28_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage9_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage28_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage28_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta10_V_V_full_n),
    .s_output_theta_V_V_write(one_stage28_U0_s_output_theta_V_V_write)
);

one_stage29 one_stage29_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage29_U0_ap_start),
    .start_full_n(start_for_one_stage30_U0_full_n),
    .ap_done(one_stage29_U0_ap_done),
    .ap_continue(one_stage29_U0_ap_continue),
    .ap_idle(one_stage29_U0_ap_idle),
    .ap_ready(one_stage29_U0_ap_ready),
    .start_out(one_stage29_U0_start_out),
    .start_write(one_stage29_U0_start_write),
    .s_current_cos_V_V_dout(Stage9_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage9_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage29_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage9_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage9_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage29_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta10_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta10_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage29_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage29_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage10_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage29_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage29_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage10_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage29_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage29_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta11_V_V_full_n),
    .s_output_theta_V_V_write(one_stage29_U0_s_output_theta_V_V_write)
);

one_stage30 one_stage30_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage30_U0_ap_start),
    .start_full_n(start_for_one_stage31_U0_full_n),
    .ap_done(one_stage30_U0_ap_done),
    .ap_continue(one_stage30_U0_ap_continue),
    .ap_idle(one_stage30_U0_ap_idle),
    .ap_ready(one_stage30_U0_ap_ready),
    .start_out(one_stage30_U0_start_out),
    .start_write(one_stage30_U0_start_write),
    .s_current_cos_V_V_dout(Stage10_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage10_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage30_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage10_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage10_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage30_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta11_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta11_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage30_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage30_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage11_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage30_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage30_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage11_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage30_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage30_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta12_V_V_full_n),
    .s_output_theta_V_V_write(one_stage30_U0_s_output_theta_V_V_write)
);

one_stage31 one_stage31_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage31_U0_ap_start),
    .start_full_n(start_for_one_stage32_U0_full_n),
    .ap_done(one_stage31_U0_ap_done),
    .ap_continue(one_stage31_U0_ap_continue),
    .ap_idle(one_stage31_U0_ap_idle),
    .ap_ready(one_stage31_U0_ap_ready),
    .start_out(one_stage31_U0_start_out),
    .start_write(one_stage31_U0_start_write),
    .s_current_cos_V_V_dout(Stage11_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage11_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage31_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage11_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage11_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage31_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta12_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta12_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage31_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage31_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage12_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage31_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage31_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage12_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage31_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage31_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta13_V_V_full_n),
    .s_output_theta_V_V_write(one_stage31_U0_s_output_theta_V_V_write)
);

one_stage32 one_stage32_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage32_U0_ap_start),
    .start_full_n(start_for_one_stage33_U0_full_n),
    .ap_done(one_stage32_U0_ap_done),
    .ap_continue(one_stage32_U0_ap_continue),
    .ap_idle(one_stage32_U0_ap_idle),
    .ap_ready(one_stage32_U0_ap_ready),
    .start_out(one_stage32_U0_start_out),
    .start_write(one_stage32_U0_start_write),
    .s_current_cos_V_V_dout(Stage12_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage12_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage32_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage12_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage12_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage32_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta13_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta13_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage32_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage32_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage13_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage32_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage32_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage13_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage32_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage32_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta14_V_V_full_n),
    .s_output_theta_V_V_write(one_stage32_U0_s_output_theta_V_V_write)
);

one_stage33 one_stage33_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage33_U0_ap_start),
    .start_full_n(start_for_one_stage34_U0_full_n),
    .ap_done(one_stage33_U0_ap_done),
    .ap_continue(one_stage33_U0_ap_continue),
    .ap_idle(one_stage33_U0_ap_idle),
    .ap_ready(one_stage33_U0_ap_ready),
    .start_out(one_stage33_U0_start_out),
    .start_write(one_stage33_U0_start_write),
    .s_current_cos_V_V_dout(Stage13_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage13_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage33_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage13_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage13_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage33_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta14_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta14_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage33_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage33_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(Stage14_COS_V_V_full_n),
    .s_output_cos_V_V_write(one_stage33_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage33_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(Stage14_Sin_V_V_full_n),
    .s_output_sin_V_V_write(one_stage33_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage33_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta15_V_V_full_n),
    .s_output_theta_V_V_write(one_stage33_U0_s_output_theta_V_V_write)
);

one_stage34 one_stage34_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(one_stage34_U0_ap_start),
    .start_full_n(start_for_Block_ap_fixed_base_1_U0_full_n),
    .ap_done(one_stage34_U0_ap_done),
    .ap_continue(one_stage34_U0_ap_continue),
    .ap_idle(one_stage34_U0_ap_idle),
    .ap_ready(one_stage34_U0_ap_ready),
    .start_out(one_stage34_U0_start_out),
    .start_write(one_stage34_U0_start_write),
    .s_current_cos_V_V_dout(Stage14_COS_V_V_dout),
    .s_current_cos_V_V_empty_n(Stage14_COS_V_V_empty_n),
    .s_current_cos_V_V_read(one_stage34_U0_s_current_cos_V_V_read),
    .s_current_sin_V_V_dout(Stage14_Sin_V_V_dout),
    .s_current_sin_V_V_empty_n(Stage14_Sin_V_V_empty_n),
    .s_current_sin_V_V_read(one_stage34_U0_s_current_sin_V_V_read),
    .s_current_theta_V_V_dout(Theta15_V_V_dout),
    .s_current_theta_V_V_empty_n(Theta15_V_V_empty_n),
    .s_current_theta_V_V_read(one_stage34_U0_s_current_theta_V_V_read),
    .s_output_cos_V_V_din(one_stage34_U0_s_output_cos_V_V_din),
    .s_output_cos_V_V_full_n(out_c_V_V_full_n),
    .s_output_cos_V_V_write(one_stage34_U0_s_output_cos_V_V_write),
    .s_output_sin_V_V_din(one_stage34_U0_s_output_sin_V_V_din),
    .s_output_sin_V_V_full_n(out_s_V_V_full_n),
    .s_output_sin_V_V_write(one_stage34_U0_s_output_sin_V_V_write),
    .s_output_theta_V_V_din(one_stage34_U0_s_output_theta_V_V_din),
    .s_output_theta_V_V_full_n(Theta16_V_V_full_n),
    .s_output_theta_V_V_write(one_stage34_U0_s_output_theta_V_V_write)
);

Block_ap_fixed_base_1 Block_ap_fixed_base_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_ap_fixed_base_1_U0_ap_start),
    .ap_done(Block_ap_fixed_base_1_U0_ap_done),
    .ap_continue(Block_ap_fixed_base_1_U0_ap_continue),
    .ap_idle(Block_ap_fixed_base_1_U0_ap_idle),
    .ap_ready(Block_ap_fixed_base_1_U0_ap_ready),
    .Theta16_V_V_dout(Theta16_V_V_dout),
    .Theta16_V_V_empty_n(Theta16_V_V_empty_n),
    .Theta16_V_V_read(Block_ap_fixed_base_1_U0_Theta16_V_V_read)
);

fifo_w10_d2_A Stage0_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ap_fixed_base_U0_Stage0_COS_V_V_din),
    .if_full_n(Stage0_COS_V_V_full_n),
    .if_write(Block_ap_fixed_base_U0_Stage0_COS_V_V_write),
    .if_dout(Stage0_COS_V_V_dout),
    .if_empty_n(Stage0_COS_V_V_empty_n),
    .if_read(one_stage20_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage0_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_ap_fixed_base_U0_Stage0_Sin_V_V_din),
    .if_full_n(Stage0_Sin_V_V_full_n),
    .if_write(Block_ap_fixed_base_U0_Stage0_Sin_V_V_write),
    .if_dout(Stage0_Sin_V_V_dout),
    .if_empty_n(Stage0_Sin_V_V_empty_n),
    .if_read(one_stage20_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Stage1_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage20_U0_s_output_cos_V_V_din),
    .if_full_n(Stage1_COS_V_V_full_n),
    .if_write(one_stage20_U0_s_output_cos_V_V_write),
    .if_dout(Stage1_COS_V_V_dout),
    .if_empty_n(Stage1_COS_V_V_empty_n),
    .if_read(one_stage21_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage1_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage20_U0_s_output_sin_V_V_din),
    .if_full_n(Stage1_Sin_V_V_full_n),
    .if_write(one_stage20_U0_s_output_sin_V_V_write),
    .if_dout(Stage1_Sin_V_V_dout),
    .if_empty_n(Stage1_Sin_V_V_empty_n),
    .if_read(one_stage21_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta2_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage20_U0_s_output_theta_V_V_din),
    .if_full_n(Theta2_V_V_full_n),
    .if_write(one_stage20_U0_s_output_theta_V_V_write),
    .if_dout(Theta2_V_V_dout),
    .if_empty_n(Theta2_V_V_empty_n),
    .if_read(one_stage21_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage2_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage21_U0_s_output_cos_V_V_din),
    .if_full_n(Stage2_COS_V_V_full_n),
    .if_write(one_stage21_U0_s_output_cos_V_V_write),
    .if_dout(Stage2_COS_V_V_dout),
    .if_empty_n(Stage2_COS_V_V_empty_n),
    .if_read(one_stage22_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage2_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage21_U0_s_output_sin_V_V_din),
    .if_full_n(Stage2_Sin_V_V_full_n),
    .if_write(one_stage21_U0_s_output_sin_V_V_write),
    .if_dout(Stage2_Sin_V_V_dout),
    .if_empty_n(Stage2_Sin_V_V_empty_n),
    .if_read(one_stage22_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta3_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage21_U0_s_output_theta_V_V_din),
    .if_full_n(Theta3_V_V_full_n),
    .if_write(one_stage21_U0_s_output_theta_V_V_write),
    .if_dout(Theta3_V_V_dout),
    .if_empty_n(Theta3_V_V_empty_n),
    .if_read(one_stage22_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage3_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage22_U0_s_output_cos_V_V_din),
    .if_full_n(Stage3_COS_V_V_full_n),
    .if_write(one_stage22_U0_s_output_cos_V_V_write),
    .if_dout(Stage3_COS_V_V_dout),
    .if_empty_n(Stage3_COS_V_V_empty_n),
    .if_read(one_stage23_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage3_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage22_U0_s_output_sin_V_V_din),
    .if_full_n(Stage3_Sin_V_V_full_n),
    .if_write(one_stage22_U0_s_output_sin_V_V_write),
    .if_dout(Stage3_Sin_V_V_dout),
    .if_empty_n(Stage3_Sin_V_V_empty_n),
    .if_read(one_stage23_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta4_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage22_U0_s_output_theta_V_V_din),
    .if_full_n(Theta4_V_V_full_n),
    .if_write(one_stage22_U0_s_output_theta_V_V_write),
    .if_dout(Theta4_V_V_dout),
    .if_empty_n(Theta4_V_V_empty_n),
    .if_read(one_stage23_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage4_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage23_U0_s_output_cos_V_V_din),
    .if_full_n(Stage4_COS_V_V_full_n),
    .if_write(one_stage23_U0_s_output_cos_V_V_write),
    .if_dout(Stage4_COS_V_V_dout),
    .if_empty_n(Stage4_COS_V_V_empty_n),
    .if_read(one_stage24_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage4_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage23_U0_s_output_sin_V_V_din),
    .if_full_n(Stage4_Sin_V_V_full_n),
    .if_write(one_stage23_U0_s_output_sin_V_V_write),
    .if_dout(Stage4_Sin_V_V_dout),
    .if_empty_n(Stage4_Sin_V_V_empty_n),
    .if_read(one_stage24_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta5_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage23_U0_s_output_theta_V_V_din),
    .if_full_n(Theta5_V_V_full_n),
    .if_write(one_stage23_U0_s_output_theta_V_V_write),
    .if_dout(Theta5_V_V_dout),
    .if_empty_n(Theta5_V_V_empty_n),
    .if_read(one_stage24_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage5_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage24_U0_s_output_cos_V_V_din),
    .if_full_n(Stage5_COS_V_V_full_n),
    .if_write(one_stage24_U0_s_output_cos_V_V_write),
    .if_dout(Stage5_COS_V_V_dout),
    .if_empty_n(Stage5_COS_V_V_empty_n),
    .if_read(one_stage25_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage5_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage24_U0_s_output_sin_V_V_din),
    .if_full_n(Stage5_Sin_V_V_full_n),
    .if_write(one_stage24_U0_s_output_sin_V_V_write),
    .if_dout(Stage5_Sin_V_V_dout),
    .if_empty_n(Stage5_Sin_V_V_empty_n),
    .if_read(one_stage25_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta6_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage24_U0_s_output_theta_V_V_din),
    .if_full_n(Theta6_V_V_full_n),
    .if_write(one_stage24_U0_s_output_theta_V_V_write),
    .if_dout(Theta6_V_V_dout),
    .if_empty_n(Theta6_V_V_empty_n),
    .if_read(one_stage25_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage6_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage25_U0_s_output_cos_V_V_din),
    .if_full_n(Stage6_COS_V_V_full_n),
    .if_write(one_stage25_U0_s_output_cos_V_V_write),
    .if_dout(Stage6_COS_V_V_dout),
    .if_empty_n(Stage6_COS_V_V_empty_n),
    .if_read(one_stage26_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage6_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage25_U0_s_output_sin_V_V_din),
    .if_full_n(Stage6_Sin_V_V_full_n),
    .if_write(one_stage25_U0_s_output_sin_V_V_write),
    .if_dout(Stage6_Sin_V_V_dout),
    .if_empty_n(Stage6_Sin_V_V_empty_n),
    .if_read(one_stage26_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta7_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage25_U0_s_output_theta_V_V_din),
    .if_full_n(Theta7_V_V_full_n),
    .if_write(one_stage25_U0_s_output_theta_V_V_write),
    .if_dout(Theta7_V_V_dout),
    .if_empty_n(Theta7_V_V_empty_n),
    .if_read(one_stage26_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage7_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage26_U0_s_output_cos_V_V_din),
    .if_full_n(Stage7_COS_V_V_full_n),
    .if_write(one_stage26_U0_s_output_cos_V_V_write),
    .if_dout(Stage7_COS_V_V_dout),
    .if_empty_n(Stage7_COS_V_V_empty_n),
    .if_read(one_stage27_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage7_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage26_U0_s_output_sin_V_V_din),
    .if_full_n(Stage7_Sin_V_V_full_n),
    .if_write(one_stage26_U0_s_output_sin_V_V_write),
    .if_dout(Stage7_Sin_V_V_dout),
    .if_empty_n(Stage7_Sin_V_V_empty_n),
    .if_read(one_stage27_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta8_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage26_U0_s_output_theta_V_V_din),
    .if_full_n(Theta8_V_V_full_n),
    .if_write(one_stage26_U0_s_output_theta_V_V_write),
    .if_dout(Theta8_V_V_dout),
    .if_empty_n(Theta8_V_V_empty_n),
    .if_read(one_stage27_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage8_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage27_U0_s_output_cos_V_V_din),
    .if_full_n(Stage8_COS_V_V_full_n),
    .if_write(one_stage27_U0_s_output_cos_V_V_write),
    .if_dout(Stage8_COS_V_V_dout),
    .if_empty_n(Stage8_COS_V_V_empty_n),
    .if_read(one_stage28_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage8_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage27_U0_s_output_sin_V_V_din),
    .if_full_n(Stage8_Sin_V_V_full_n),
    .if_write(one_stage27_U0_s_output_sin_V_V_write),
    .if_dout(Stage8_Sin_V_V_dout),
    .if_empty_n(Stage8_Sin_V_V_empty_n),
    .if_read(one_stage28_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta9_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage27_U0_s_output_theta_V_V_din),
    .if_full_n(Theta9_V_V_full_n),
    .if_write(one_stage27_U0_s_output_theta_V_V_write),
    .if_dout(Theta9_V_V_dout),
    .if_empty_n(Theta9_V_V_empty_n),
    .if_read(one_stage28_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage9_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage28_U0_s_output_cos_V_V_din),
    .if_full_n(Stage9_COS_V_V_full_n),
    .if_write(one_stage28_U0_s_output_cos_V_V_write),
    .if_dout(Stage9_COS_V_V_dout),
    .if_empty_n(Stage9_COS_V_V_empty_n),
    .if_read(one_stage29_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage9_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage28_U0_s_output_sin_V_V_din),
    .if_full_n(Stage9_Sin_V_V_full_n),
    .if_write(one_stage28_U0_s_output_sin_V_V_write),
    .if_dout(Stage9_Sin_V_V_dout),
    .if_empty_n(Stage9_Sin_V_V_empty_n),
    .if_read(one_stage29_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta10_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage28_U0_s_output_theta_V_V_din),
    .if_full_n(Theta10_V_V_full_n),
    .if_write(one_stage28_U0_s_output_theta_V_V_write),
    .if_dout(Theta10_V_V_dout),
    .if_empty_n(Theta10_V_V_empty_n),
    .if_read(one_stage29_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage10_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage29_U0_s_output_cos_V_V_din),
    .if_full_n(Stage10_COS_V_V_full_n),
    .if_write(one_stage29_U0_s_output_cos_V_V_write),
    .if_dout(Stage10_COS_V_V_dout),
    .if_empty_n(Stage10_COS_V_V_empty_n),
    .if_read(one_stage30_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage10_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage29_U0_s_output_sin_V_V_din),
    .if_full_n(Stage10_Sin_V_V_full_n),
    .if_write(one_stage29_U0_s_output_sin_V_V_write),
    .if_dout(Stage10_Sin_V_V_dout),
    .if_empty_n(Stage10_Sin_V_V_empty_n),
    .if_read(one_stage30_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta11_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage29_U0_s_output_theta_V_V_din),
    .if_full_n(Theta11_V_V_full_n),
    .if_write(one_stage29_U0_s_output_theta_V_V_write),
    .if_dout(Theta11_V_V_dout),
    .if_empty_n(Theta11_V_V_empty_n),
    .if_read(one_stage30_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage11_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage30_U0_s_output_cos_V_V_din),
    .if_full_n(Stage11_COS_V_V_full_n),
    .if_write(one_stage30_U0_s_output_cos_V_V_write),
    .if_dout(Stage11_COS_V_V_dout),
    .if_empty_n(Stage11_COS_V_V_empty_n),
    .if_read(one_stage31_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage11_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage30_U0_s_output_sin_V_V_din),
    .if_full_n(Stage11_Sin_V_V_full_n),
    .if_write(one_stage30_U0_s_output_sin_V_V_write),
    .if_dout(Stage11_Sin_V_V_dout),
    .if_empty_n(Stage11_Sin_V_V_empty_n),
    .if_read(one_stage31_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta12_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage30_U0_s_output_theta_V_V_din),
    .if_full_n(Theta12_V_V_full_n),
    .if_write(one_stage30_U0_s_output_theta_V_V_write),
    .if_dout(Theta12_V_V_dout),
    .if_empty_n(Theta12_V_V_empty_n),
    .if_read(one_stage31_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage12_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage31_U0_s_output_cos_V_V_din),
    .if_full_n(Stage12_COS_V_V_full_n),
    .if_write(one_stage31_U0_s_output_cos_V_V_write),
    .if_dout(Stage12_COS_V_V_dout),
    .if_empty_n(Stage12_COS_V_V_empty_n),
    .if_read(one_stage32_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage12_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage31_U0_s_output_sin_V_V_din),
    .if_full_n(Stage12_Sin_V_V_full_n),
    .if_write(one_stage31_U0_s_output_sin_V_V_write),
    .if_dout(Stage12_Sin_V_V_dout),
    .if_empty_n(Stage12_Sin_V_V_empty_n),
    .if_read(one_stage32_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta13_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage31_U0_s_output_theta_V_V_din),
    .if_full_n(Theta13_V_V_full_n),
    .if_write(one_stage31_U0_s_output_theta_V_V_write),
    .if_dout(Theta13_V_V_dout),
    .if_empty_n(Theta13_V_V_empty_n),
    .if_read(one_stage32_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage13_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage32_U0_s_output_cos_V_V_din),
    .if_full_n(Stage13_COS_V_V_full_n),
    .if_write(one_stage32_U0_s_output_cos_V_V_write),
    .if_dout(Stage13_COS_V_V_dout),
    .if_empty_n(Stage13_COS_V_V_empty_n),
    .if_read(one_stage33_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage13_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage32_U0_s_output_sin_V_V_din),
    .if_full_n(Stage13_Sin_V_V_full_n),
    .if_write(one_stage32_U0_s_output_sin_V_V_write),
    .if_dout(Stage13_Sin_V_V_dout),
    .if_empty_n(Stage13_Sin_V_V_empty_n),
    .if_read(one_stage33_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta14_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage32_U0_s_output_theta_V_V_din),
    .if_full_n(Theta14_V_V_full_n),
    .if_write(one_stage32_U0_s_output_theta_V_V_write),
    .if_dout(Theta14_V_V_dout),
    .if_empty_n(Theta14_V_V_empty_n),
    .if_read(one_stage33_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Stage14_COS_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage33_U0_s_output_cos_V_V_din),
    .if_full_n(Stage14_COS_V_V_full_n),
    .if_write(one_stage33_U0_s_output_cos_V_V_write),
    .if_dout(Stage14_COS_V_V_dout),
    .if_empty_n(Stage14_COS_V_V_empty_n),
    .if_read(one_stage34_U0_s_current_cos_V_V_read)
);

fifo_w10_d2_A Stage14_Sin_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage33_U0_s_output_sin_V_V_din),
    .if_full_n(Stage14_Sin_V_V_full_n),
    .if_write(one_stage33_U0_s_output_sin_V_V_write),
    .if_dout(Stage14_Sin_V_V_dout),
    .if_empty_n(Stage14_Sin_V_V_empty_n),
    .if_read(one_stage34_U0_s_current_sin_V_V_read)
);

fifo_w10_d2_A Theta15_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage33_U0_s_output_theta_V_V_din),
    .if_full_n(Theta15_V_V_full_n),
    .if_write(one_stage33_U0_s_output_theta_V_V_write),
    .if_dout(Theta15_V_V_dout),
    .if_empty_n(Theta15_V_V_empty_n),
    .if_read(one_stage34_U0_s_current_theta_V_V_read)
);

fifo_w10_d2_A Theta16_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(one_stage34_U0_s_output_theta_V_V_din),
    .if_full_n(Theta16_V_V_full_n),
    .if_write(one_stage34_U0_s_output_theta_V_V_write),
    .if_dout(Theta16_V_V_dout),
    .if_empty_n(Theta16_V_V_empty_n),
    .if_read(Block_ap_fixed_base_1_U0_Theta16_V_V_read)
);

start_for_one_stabkb start_for_one_stabkb_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage21_U0_din),
    .if_full_n(start_for_one_stage21_U0_full_n),
    .if_write(one_stage20_U0_start_write),
    .if_dout(start_for_one_stage21_U0_dout),
    .if_empty_n(start_for_one_stage21_U0_empty_n),
    .if_read(one_stage21_U0_ap_ready)
);

start_for_one_stacud start_for_one_stacud_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage22_U0_din),
    .if_full_n(start_for_one_stage22_U0_full_n),
    .if_write(one_stage21_U0_start_write),
    .if_dout(start_for_one_stage22_U0_dout),
    .if_empty_n(start_for_one_stage22_U0_empty_n),
    .if_read(one_stage22_U0_ap_ready)
);

start_for_one_stadEe start_for_one_stadEe_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage23_U0_din),
    .if_full_n(start_for_one_stage23_U0_full_n),
    .if_write(one_stage22_U0_start_write),
    .if_dout(start_for_one_stage23_U0_dout),
    .if_empty_n(start_for_one_stage23_U0_empty_n),
    .if_read(one_stage23_U0_ap_ready)
);

start_for_one_staeOg start_for_one_staeOg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage24_U0_din),
    .if_full_n(start_for_one_stage24_U0_full_n),
    .if_write(one_stage23_U0_start_write),
    .if_dout(start_for_one_stage24_U0_dout),
    .if_empty_n(start_for_one_stage24_U0_empty_n),
    .if_read(one_stage24_U0_ap_ready)
);

start_for_one_stafYi start_for_one_stafYi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage25_U0_din),
    .if_full_n(start_for_one_stage25_U0_full_n),
    .if_write(one_stage24_U0_start_write),
    .if_dout(start_for_one_stage25_U0_dout),
    .if_empty_n(start_for_one_stage25_U0_empty_n),
    .if_read(one_stage25_U0_ap_ready)
);

start_for_one_stag8j start_for_one_stag8j_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage26_U0_din),
    .if_full_n(start_for_one_stage26_U0_full_n),
    .if_write(one_stage25_U0_start_write),
    .if_dout(start_for_one_stage26_U0_dout),
    .if_empty_n(start_for_one_stage26_U0_empty_n),
    .if_read(one_stage26_U0_ap_ready)
);

start_for_one_stahbi start_for_one_stahbi_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage27_U0_din),
    .if_full_n(start_for_one_stage27_U0_full_n),
    .if_write(one_stage26_U0_start_write),
    .if_dout(start_for_one_stage27_U0_dout),
    .if_empty_n(start_for_one_stage27_U0_empty_n),
    .if_read(one_stage27_U0_ap_ready)
);

start_for_one_staibs start_for_one_staibs_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage28_U0_din),
    .if_full_n(start_for_one_stage28_U0_full_n),
    .if_write(one_stage27_U0_start_write),
    .if_dout(start_for_one_stage28_U0_dout),
    .if_empty_n(start_for_one_stage28_U0_empty_n),
    .if_read(one_stage28_U0_ap_ready)
);

start_for_one_stajbC start_for_one_stajbC_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage29_U0_din),
    .if_full_n(start_for_one_stage29_U0_full_n),
    .if_write(one_stage28_U0_start_write),
    .if_dout(start_for_one_stage29_U0_dout),
    .if_empty_n(start_for_one_stage29_U0_empty_n),
    .if_read(one_stage29_U0_ap_ready)
);

start_for_one_stakbM start_for_one_stakbM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage30_U0_din),
    .if_full_n(start_for_one_stage30_U0_full_n),
    .if_write(one_stage29_U0_start_write),
    .if_dout(start_for_one_stage30_U0_dout),
    .if_empty_n(start_for_one_stage30_U0_empty_n),
    .if_read(one_stage30_U0_ap_ready)
);

start_for_one_stalbW start_for_one_stalbW_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage31_U0_din),
    .if_full_n(start_for_one_stage31_U0_full_n),
    .if_write(one_stage30_U0_start_write),
    .if_dout(start_for_one_stage31_U0_dout),
    .if_empty_n(start_for_one_stage31_U0_empty_n),
    .if_read(one_stage31_U0_ap_ready)
);

start_for_one_stamb6 start_for_one_stamb6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage32_U0_din),
    .if_full_n(start_for_one_stage32_U0_full_n),
    .if_write(one_stage31_U0_start_write),
    .if_dout(start_for_one_stage32_U0_dout),
    .if_empty_n(start_for_one_stage32_U0_empty_n),
    .if_read(one_stage32_U0_ap_ready)
);

start_for_one_stancg start_for_one_stancg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage33_U0_din),
    .if_full_n(start_for_one_stage33_U0_full_n),
    .if_write(one_stage32_U0_start_write),
    .if_dout(start_for_one_stage33_U0_dout),
    .if_empty_n(start_for_one_stage33_U0_empty_n),
    .if_read(one_stage33_U0_ap_ready)
);

start_for_one_staocq start_for_one_staocq_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_one_stage34_U0_din),
    .if_full_n(start_for_one_stage34_U0_full_n),
    .if_write(one_stage33_U0_start_write),
    .if_dout(start_for_one_stage34_U0_dout),
    .if_empty_n(start_for_one_stage34_U0_empty_n),
    .if_read(one_stage34_U0_ap_ready)
);

start_for_Block_apcA start_for_Block_apcA_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_ap_fixed_base_1_U0_din),
    .if_full_n(start_for_Block_ap_fixed_base_1_U0_full_n),
    .if_write(one_stage34_U0_start_write),
    .if_dout(start_for_Block_ap_fixed_base_1_U0_dout),
    .if_empty_n(start_for_Block_ap_fixed_base_1_U0_empty_n),
    .if_read(Block_ap_fixed_base_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_Block_ap_fixed_base_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_ap_fixed_base_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_ap_fixed_base_U0_ap_ready <= ap_sync_Block_ap_fixed_base_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_one_stage20_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_one_stage20_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_one_stage20_U0_ap_ready <= ap_sync_one_stage20_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == Block_ap_fixed_base_U0_ap_ready) & (ap_sync_ready == 1'b1))) begin
        Block_ap_fixed_base_U0_ap_ready_count <= (Block_ap_fixed_base_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == Block_ap_fixed_base_U0_ap_ready))) begin
        Block_ap_fixed_base_U0_ap_ready_count <= (Block_ap_fixed_base_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((one_stage20_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        one_stage20_U0_ap_ready_count <= (one_stage20_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (one_stage20_U0_ap_ready == 1'b1))) begin
        one_stage20_U0_ap_ready_count <= (one_stage20_U0_ap_ready_count + 2'd1);
    end
end

assign Block_ap_fixed_base_1_U0_ap_continue = ap_sync_done;

assign Block_ap_fixed_base_1_U0_ap_start = start_for_Block_ap_fixed_base_1_U0_empty_n;

assign Block_ap_fixed_base_1_U0_start_full_n = 1'b1;

assign Block_ap_fixed_base_1_U0_start_write = 1'b0;

assign Block_ap_fixed_base_U0_ap_continue = 1'b1;

assign Block_ap_fixed_base_U0_ap_start = ((ap_sync_reg_Block_ap_fixed_base_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_ap_fixed_base_U0_start_full_n = 1'b1;

assign Block_ap_fixed_base_U0_start_write = 1'b0;

assign ap_done = ap_sync_done;

assign ap_idle = (one_stage34_U0_ap_idle & one_stage33_U0_ap_idle & one_stage32_U0_ap_idle & one_stage31_U0_ap_idle & one_stage30_U0_ap_idle & one_stage29_U0_ap_idle & one_stage28_U0_ap_idle & one_stage27_U0_ap_idle & one_stage26_U0_ap_idle & one_stage25_U0_ap_idle & one_stage24_U0_ap_idle & one_stage23_U0_ap_idle & one_stage22_U0_ap_idle & one_stage21_U0_ap_idle & one_stage20_U0_ap_idle & Block_ap_fixed_base_U0_ap_idle & Block_ap_fixed_base_1_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_Block_ap_fixed_base_U0_ap_ready = (ap_sync_reg_Block_ap_fixed_base_U0_ap_ready | Block_ap_fixed_base_U0_ap_ready);

assign ap_sync_continue = ap_sync_done;

assign ap_sync_done = (one_stage34_U0_ap_done & Block_ap_fixed_base_1_U0_ap_done);

assign ap_sync_one_stage20_U0_ap_ready = (one_stage20_U0_ap_ready | ap_sync_reg_one_stage20_U0_ap_ready);

assign ap_sync_ready = (ap_sync_one_stage20_U0_ap_ready & ap_sync_Block_ap_fixed_base_U0_ap_ready);

assign in_theta_V_V_read = one_stage20_U0_s_current_theta_V_V_read;

assign one_stage20_U0_ap_continue = 1'b1;

assign one_stage20_U0_ap_start = ((ap_sync_reg_one_stage20_U0_ap_ready ^ 1'b1) & ap_start);

assign one_stage21_U0_ap_continue = 1'b1;

assign one_stage21_U0_ap_start = start_for_one_stage21_U0_empty_n;

assign one_stage22_U0_ap_continue = 1'b1;

assign one_stage22_U0_ap_start = start_for_one_stage22_U0_empty_n;

assign one_stage23_U0_ap_continue = 1'b1;

assign one_stage23_U0_ap_start = start_for_one_stage23_U0_empty_n;

assign one_stage24_U0_ap_continue = 1'b1;

assign one_stage24_U0_ap_start = start_for_one_stage24_U0_empty_n;

assign one_stage25_U0_ap_continue = 1'b1;

assign one_stage25_U0_ap_start = start_for_one_stage25_U0_empty_n;

assign one_stage26_U0_ap_continue = 1'b1;

assign one_stage26_U0_ap_start = start_for_one_stage26_U0_empty_n;

assign one_stage27_U0_ap_continue = 1'b1;

assign one_stage27_U0_ap_start = start_for_one_stage27_U0_empty_n;

assign one_stage28_U0_ap_continue = 1'b1;

assign one_stage28_U0_ap_start = start_for_one_stage28_U0_empty_n;

assign one_stage29_U0_ap_continue = 1'b1;

assign one_stage29_U0_ap_start = start_for_one_stage29_U0_empty_n;

assign one_stage30_U0_ap_continue = 1'b1;

assign one_stage30_U0_ap_start = start_for_one_stage30_U0_empty_n;

assign one_stage31_U0_ap_continue = 1'b1;

assign one_stage31_U0_ap_start = start_for_one_stage31_U0_empty_n;

assign one_stage32_U0_ap_continue = 1'b1;

assign one_stage32_U0_ap_start = start_for_one_stage32_U0_empty_n;

assign one_stage33_U0_ap_continue = 1'b1;

assign one_stage33_U0_ap_start = start_for_one_stage33_U0_empty_n;

assign one_stage34_U0_ap_continue = ap_sync_done;

assign one_stage34_U0_ap_start = start_for_one_stage34_U0_empty_n;

assign out_c_V_V_din = one_stage34_U0_s_output_cos_V_V_din;

assign out_c_V_V_write = one_stage34_U0_s_output_cos_V_V_write;

assign out_s_V_V_din = one_stage34_U0_s_output_sin_V_V_din;

assign out_s_V_V_write = one_stage34_U0_s_output_sin_V_V_write;

assign start_for_Block_ap_fixed_base_1_U0_din = 1'b1;

assign start_for_one_stage21_U0_din = 1'b1;

assign start_for_one_stage22_U0_din = 1'b1;

assign start_for_one_stage23_U0_din = 1'b1;

assign start_for_one_stage24_U0_din = 1'b1;

assign start_for_one_stage25_U0_din = 1'b1;

assign start_for_one_stage26_U0_din = 1'b1;

assign start_for_one_stage27_U0_din = 1'b1;

assign start_for_one_stage28_U0_din = 1'b1;

assign start_for_one_stage29_U0_din = 1'b1;

assign start_for_one_stage30_U0_din = 1'b1;

assign start_for_one_stage31_U0_din = 1'b1;

assign start_for_one_stage32_U0_din = 1'b1;

assign start_for_one_stage33_U0_din = 1'b1;

assign start_for_one_stage34_U0_din = 1'b1;

endmodule //cordic
