// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module histogram_histogram_map3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        inputA_address0,
        inputA_ce0,
        inputA_q0,
        hist_address0,
        hist_ce0,
        hist_we0,
        hist_d0,
        hist_address1,
        hist_ce1,
        hist_q1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [9:0] inputA_address0;
output   inputA_ce0;
input  [31:0] inputA_q0;
output  [4:0] hist_address0;
output   hist_ce0;
output   hist_we0;
output  [31:0] hist_d0;
output  [4:0] hist_address1;
output   hist_ce1;
input  [31:0] hist_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] inputA_address0;
reg inputA_ce0;
reg[4:0] hist_address0;
reg hist_ce0;
reg hist_we0;
reg[31:0] hist_d0;
reg hist_ce1;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] old_reg_103;
wire    ap_CS_fsm_state2;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_done;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_idle;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_ready;
wire   [4:0] grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_address0;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_ce0;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_we0;
wire   [31:0] grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_d0;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_done;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_idle;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_ready;
wire   [9:0] grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_inputA_address0;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_inputA_ce0;
wire   [4:0] grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_address0;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_ce0;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_we0;
wire   [31:0] grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_d0;
wire   [4:0] grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_address1;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_ce1;
wire   [31:0] grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_acc_out;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_acc_out_ap_vld;
wire   [4:0] grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_old_1_out;
wire    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_old_1_out_ap_vld;
reg    grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start_reg;
reg    ap_block_state1_ignore_call3;
reg    grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [4:0] old_1_loc_fu_22;
wire   [63:0] zext_ln21_fu_81_p1;
wire    ap_CS_fsm_state5;
reg    ap_block_state1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start_reg = 1'b0;
#0 grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start_reg = 1'b0;
end

histogram_histogram_map3_Pipeline_VITIS_LOOP_4_1 grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start),
    .ap_done(grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_done),
    .ap_idle(grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_idle),
    .ap_ready(grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_ready),
    .hist_address0(grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_address0),
    .hist_ce0(grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_ce0),
    .hist_we0(grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_we0),
    .hist_d0(grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_d0)
);

histogram_histogram_map3_Pipeline_VITIS_LOOP_10_2 grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start),
    .ap_done(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_done),
    .ap_idle(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_idle),
    .ap_ready(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_ready),
    .old(old_reg_103),
    .inputA_address0(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_inputA_address0),
    .inputA_ce0(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_inputA_ce0),
    .inputA_q0(inputA_q0),
    .hist_address0(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_address0),
    .hist_ce0(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_ce0),
    .hist_we0(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_we0),
    .hist_d0(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_d0),
    .hist_address1(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_address1),
    .hist_ce1(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_ce1),
    .hist_q1(hist_q1),
    .acc_out(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_acc_out),
    .acc_out_ap_vld(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_acc_out_ap_vld),
    .old_1_out(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_old_1_out),
    .old_1_out_ap_vld(grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_old_1_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start_reg <= 1'b1;
        end else if ((grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_ready == 1'b1)) begin
            grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start_reg <= 1'b1;
        end else if ((grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_ready == 1'b1)) begin
            grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_old_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        old_1_loc_fu_22 <= grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_old_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        old_reg_103 <= inputA_q0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hist_address0 = zext_ln21_fu_81_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hist_address0 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_address0 = grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_address0;
    end else begin
        hist_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hist_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hist_ce0 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_ce0 = grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_ce0;
    end else begin
        hist_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hist_ce1 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_ce1;
    end else begin
        hist_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hist_d0 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_acc_out;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hist_d0 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_d0 = grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_d0;
    end else begin
        hist_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hist_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        hist_we0 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        hist_we0 = grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_hist_we0;
    end else begin
        hist_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        inputA_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        inputA_address0 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_inputA_address0;
    end else begin
        inputA_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        inputA_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        inputA_ce0 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_inputA_ce0;
    end else begin
        inputA_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call3 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_ap_start_reg;

assign grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start = grp_histogram_map3_Pipeline_VITIS_LOOP_4_1_fu_57_ap_start_reg;

assign hist_address1 = grp_histogram_map3_Pipeline_VITIS_LOOP_10_2_fu_63_hist_address1;

assign zext_ln21_fu_81_p1 = old_1_loc_fu_22;

endmodule //histogram_histogram_map3
