-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity one_stage34 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    s_current_cos_V_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    s_current_cos_V_V_empty_n : IN STD_LOGIC;
    s_current_cos_V_V_read : OUT STD_LOGIC;
    s_current_sin_V_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    s_current_sin_V_V_empty_n : IN STD_LOGIC;
    s_current_sin_V_V_read : OUT STD_LOGIC;
    s_current_theta_V_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    s_current_theta_V_V_empty_n : IN STD_LOGIC;
    s_current_theta_V_V_read : OUT STD_LOGIC;
    s_output_cos_V_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    s_output_cos_V_V_full_n : IN STD_LOGIC;
    s_output_cos_V_V_write : OUT STD_LOGIC;
    s_output_sin_V_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    s_output_sin_V_V_full_n : IN STD_LOGIC;
    s_output_sin_V_V_write : OUT STD_LOGIC;
    s_output_theta_V_V_din : OUT STD_LOGIC_VECTOR (9 downto 0);
    s_output_theta_V_V_full_n : IN STD_LOGIC;
    s_output_theta_V_V_write : OUT STD_LOGIC );
end;


architecture behav of one_stage34 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal s_current_cos_V_V_blk_n : STD_LOGIC;
    signal s_current_sin_V_V_blk_n : STD_LOGIC;
    signal s_current_theta_V_V_blk_n : STD_LOGIC;
    signal s_output_cos_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_2_reg_164 : STD_LOGIC_VECTOR (0 downto 0);
    signal s_output_sin_V_V_blk_n : STD_LOGIC;
    signal s_output_theta_V_V_blk_n : STD_LOGIC;
    signal tmp_V_8_reg_135 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal tmp_V_9_reg_141 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_V_7_reg_147 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_fu_83_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_reg_152 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_1_fu_99_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_1_reg_158 : STD_LOGIC_VECTOR (9 downto 0);
    signal c_V_fu_115_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal c_V_1_fu_125_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal s_V_fu_120_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal s_V_1_fu_130_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_75_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_91_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_condition_122 : BOOLEAN;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((real_start = ap_const_logic_0) or (s_current_theta_V_V_empty_n = ap_const_logic_0) or (s_current_sin_V_V_empty_n = ap_const_logic_0) or (s_current_cos_V_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                r_V_1_reg_158 <= r_V_1_fu_99_p3;
                r_V_reg_152 <= r_V_fu_83_p3;
                tmp_2_reg_164 <= s_current_theta_V_V_dout(9 downto 9);
                tmp_V_7_reg_147 <= s_current_theta_V_V_dout;
                tmp_V_8_reg_135 <= s_current_cos_V_V_dout;
                tmp_V_9_reg_141 <= s_current_sin_V_V_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, s_current_cos_V_V_empty_n, s_current_sin_V_V_empty_n, s_current_theta_V_V_empty_n, s_output_cos_V_V_full_n, s_output_sin_V_V_full_n, s_output_theta_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (s_current_theta_V_V_empty_n = ap_const_logic_0) or (s_current_sin_V_V_empty_n = ap_const_logic_0) or (s_current_cos_V_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, s_current_cos_V_V_empty_n, s_current_sin_V_V_empty_n, s_current_theta_V_V_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (s_current_theta_V_V_empty_n = ap_const_logic_0) or (s_current_sin_V_V_empty_n = ap_const_logic_0) or (s_current_cos_V_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(s_output_cos_V_V_full_n, s_output_sin_V_V_full_n, s_output_theta_V_V_full_n, tmp_2_reg_164)
    begin
                ap_block_state2 <= (((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)));
    end process;


    ap_condition_122_assign_proc : process(s_output_cos_V_V_full_n, s_output_sin_V_V_full_n, s_output_theta_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
                ap_condition_122 <= (not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2));
    end process;


    ap_done_assign_proc : process(ap_done_reg, s_output_cos_V_V_full_n, s_output_sin_V_V_full_n, s_output_theta_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        if ((not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    c_V_1_fu_125_p2 <= std_logic_vector(unsigned(tmp_V_8_reg_135) + unsigned(r_V_1_reg_158));
    c_V_fu_115_p2 <= std_logic_vector(unsigned(tmp_V_8_reg_135) - unsigned(r_V_1_reg_158));

    internal_ap_ready_assign_proc : process(s_output_cos_V_V_full_n, s_output_sin_V_V_full_n, s_output_theta_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        if ((not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    r_V_1_fu_99_p3 <= 
        ap_const_lv10_3FF when (tmp_1_fu_91_p3(0) = '1') else 
        ap_const_lv10_0;
    r_V_fu_83_p3 <= 
        ap_const_lv10_3FF when (tmp_fu_75_p3(0) = '1') else 
        ap_const_lv10_0;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    s_V_1_fu_130_p2 <= std_logic_vector(unsigned(tmp_V_9_reg_141) - unsigned(r_V_reg_152));
    s_V_fu_120_p2 <= std_logic_vector(unsigned(tmp_V_9_reg_141) + unsigned(r_V_reg_152));

    s_current_cos_V_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, s_current_cos_V_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_current_cos_V_V_blk_n <= s_current_cos_V_V_empty_n;
        else 
            s_current_cos_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_current_cos_V_V_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, s_current_cos_V_V_empty_n, s_current_sin_V_V_empty_n, s_current_theta_V_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (s_current_theta_V_V_empty_n = ap_const_logic_0) or (s_current_sin_V_V_empty_n = ap_const_logic_0) or (s_current_cos_V_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_current_cos_V_V_read <= ap_const_logic_1;
        else 
            s_current_cos_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    s_current_sin_V_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, s_current_sin_V_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_current_sin_V_V_blk_n <= s_current_sin_V_V_empty_n;
        else 
            s_current_sin_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_current_sin_V_V_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, s_current_cos_V_V_empty_n, s_current_sin_V_V_empty_n, s_current_theta_V_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (s_current_theta_V_V_empty_n = ap_const_logic_0) or (s_current_sin_V_V_empty_n = ap_const_logic_0) or (s_current_cos_V_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_current_sin_V_V_read <= ap_const_logic_1;
        else 
            s_current_sin_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    s_current_theta_V_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, s_current_theta_V_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_current_theta_V_V_blk_n <= s_current_theta_V_V_empty_n;
        else 
            s_current_theta_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_current_theta_V_V_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, s_current_cos_V_V_empty_n, s_current_sin_V_V_empty_n, s_current_theta_V_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (s_current_theta_V_V_empty_n = ap_const_logic_0) or (s_current_sin_V_V_empty_n = ap_const_logic_0) or (s_current_cos_V_V_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            s_current_theta_V_V_read <= ap_const_logic_1;
        else 
            s_current_theta_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    s_output_cos_V_V_blk_n_assign_proc : process(s_output_cos_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        if ((((tmp_2_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            s_output_cos_V_V_blk_n <= s_output_cos_V_V_full_n;
        else 
            s_output_cos_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_output_cos_V_V_din_assign_proc : process(tmp_2_reg_164, c_V_fu_115_p2, c_V_1_fu_125_p2, ap_condition_122)
    begin
        if ((ap_const_boolean_1 = ap_condition_122)) then
            if ((tmp_2_reg_164 = ap_const_lv1_1)) then 
                s_output_cos_V_V_din <= c_V_1_fu_125_p2;
            elsif ((tmp_2_reg_164 = ap_const_lv1_0)) then 
                s_output_cos_V_V_din <= c_V_fu_115_p2;
            else 
                s_output_cos_V_V_din <= "XXXXXXXXXX";
            end if;
        else 
            s_output_cos_V_V_din <= "XXXXXXXXXX";
        end if; 
    end process;


    s_output_cos_V_V_write_assign_proc : process(s_output_cos_V_V_full_n, s_output_sin_V_V_full_n, s_output_theta_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        if (((not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (tmp_2_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (tmp_2_reg_164 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            s_output_cos_V_V_write <= ap_const_logic_1;
        else 
            s_output_cos_V_V_write <= ap_const_logic_0;
        end if; 
    end process;


    s_output_sin_V_V_blk_n_assign_proc : process(s_output_sin_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        if ((((tmp_2_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            s_output_sin_V_V_blk_n <= s_output_sin_V_V_full_n;
        else 
            s_output_sin_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_output_sin_V_V_din_assign_proc : process(tmp_2_reg_164, s_V_fu_120_p2, s_V_1_fu_130_p2, ap_condition_122)
    begin
        if ((ap_const_boolean_1 = ap_condition_122)) then
            if ((tmp_2_reg_164 = ap_const_lv1_1)) then 
                s_output_sin_V_V_din <= s_V_1_fu_130_p2;
            elsif ((tmp_2_reg_164 = ap_const_lv1_0)) then 
                s_output_sin_V_V_din <= s_V_fu_120_p2;
            else 
                s_output_sin_V_V_din <= "XXXXXXXXXX";
            end if;
        else 
            s_output_sin_V_V_din <= "XXXXXXXXXX";
        end if; 
    end process;


    s_output_sin_V_V_write_assign_proc : process(s_output_cos_V_V_full_n, s_output_sin_V_V_full_n, s_output_theta_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        if (((not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (tmp_2_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (tmp_2_reg_164 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            s_output_sin_V_V_write <= ap_const_logic_1;
        else 
            s_output_sin_V_V_write <= ap_const_logic_0;
        end if; 
    end process;


    s_output_theta_V_V_blk_n_assign_proc : process(s_output_theta_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        if ((((tmp_2_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            s_output_theta_V_V_blk_n <= s_output_theta_V_V_full_n;
        else 
            s_output_theta_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_output_theta_V_V_din <= tmp_V_7_reg_147;

    s_output_theta_V_V_write_assign_proc : process(s_output_cos_V_V_full_n, s_output_sin_V_V_full_n, s_output_theta_V_V_full_n, ap_CS_fsm_state2, tmp_2_reg_164)
    begin
        if (((not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (tmp_2_reg_164 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not((((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_1) and (s_output_cos_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_theta_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_sin_V_V_full_n = ap_const_logic_0)) or ((tmp_2_reg_164 = ap_const_lv1_0) and (s_output_cos_V_V_full_n = ap_const_logic_0)))) and (tmp_2_reg_164 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            s_output_theta_V_V_write <= ap_const_logic_1;
        else 
            s_output_theta_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_1_fu_91_p3 <= s_current_sin_V_V_dout(9 downto 9);
    tmp_fu_75_p3 <= s_current_cos_V_V_dout(9 downto 9);
end behav;
